version: 2

models:

  - name: gold_vti_vjp_plan_actual
    columns:
      - name: date
        test:
          - not_null

      - name: value

      - name: value_type

      - name: expense_code

      - name: expense_type_5_id

      - name: expense_type_5_name

      - name: department_code

      - name: business_unit_1_id

      - name: business_unit_1_name

      - name: business_unit_2_id

      - name: business_unit_2_name

      - name: business_unit_3_name

      - name: ob_code

      - name: source

      - name: previous_value

      - name: str_value


  - name: gold_vti_tvn_plan_actual
    columns:
      - name: date
        test:
          - not_null

      - name: value

      - name: value_type

      - name: expense_code

      - name: expense_type_5_id

      - name: expense_type_5_name

      - name: department_code

      - name: business_unit_1_id

      - name: business_unit_1_name

      - name: business_unit_2_id

      - name: business_unit_2_name

      - name: business_unit_3_name

      - name: ob_code

      - name: source

      - name: previous_value

      - name: str_value


  - name: gold_vti_edu_plan_actual
    columns:
      - name: date
        test:
          - not_null

      - name: value

      - name: value_type

      - name: expense_code

      - name: expense_type_5_id

      - name: expense_type_5_name

      - name: department_code

      - name: business_unit_1_id

      - name: business_unit_1_name

      - name: business_unit_2_id

      - name: business_unit_2_name

      - name: business_unit_3_name

      - name: ob_code

      - name: source

      - name: previous_value

      - name: str_value

  - name: gold_vti_gits_plan_actual
    columns:
      - name: date
        test:
          - not_null

      - name: value

      - name: value_type

      - name: expense_code

      - name: expense_type_5_id

      - name: expense_type_5_name

      - name: department_code

      - name: business_unit_1_id

      - name: business_unit_1_name

      - name: business_unit_2_id

      - name: business_unit_2_name

      - name: business_unit_3_name

      - name: ob_code

      - name: source

      - name: previous_value

      - name: str_value

  - name: gold_vti_snp_plan_actual
    columns:
      - name: date
        test:
          - not_null

      - name: value

      - name: value_type

      - name: expense_code

      - name: expense_type_5_id

      - name: expense_type_5_name

      - name: department_code

      - name: business_unit_1_id

      - name: business_unit_1_name

      - name: business_unit_2_id

      - name: business_unit_2_name

      - name: business_unit_3_name

      - name: ob_code

      - name: source

      - name: previous_value

      - name: str_value

  - name: gold_vti_apac_plan_actual
    columns:
      - name: date
        test:
          - not_null

      - name: value

      - name: value_type

      - name: expense_code

      - name: expense_type_5_id

      - name: expense_type_5_name

      - name: department_code

      - name: business_unit_1_id

      - name: business_unit_1_name

      - name: business_unit_2_id

      - name: business_unit_2_name

      - name: business_unit_3_id

      - name: business_unit_3_name

      - name: ob_code

      - name: previous_value

      - name: str_value


  - name: gold_vti_vn_plan_actual
    columns:
      - name: date
        test:
          - not_null

      - name: value

      - name: value_type

      - name: expense_code

      - name: expense_type_5_id

      - name: expense_type_5_name

      - name: department_code

      - name: business_unit_1_id

      - name: business_unit_1_name

      - name: business_unit_2_id

      - name: business_unit_2_name

      - name: business_unit_3_name

      - name: ob_code

      - name: source

      - name: previous_value

  - name: gold_vti_vkr_plan_actual
    columns:
      - name: date
        test:
          - not_null

      - name: value

      - name: value_type

      - name: expense_code

      - name: expense_type_5_id

      - name: expense_type_5_name

      - name: department_code

      - name: business_unit_1_id

      - name: business_unit_1_name

      - name: business_unit_2_id

      - name: business_unit_2_name

      - name: business_unit_3_name

      - name: ob_code

      - name: source

      - name: previous_value

      - name: str_value

  - name: gold_vti_conso_plan_actual
    columns:
      - name: date
        test:
          - not_null

      - name: value

      - name: value_type

      - name: expense_code

      - name: expense_type_5_id

      - name: expense_type_5_name

      - name: department_code

      - name: business_unit_1_id

      - name: business_unit_1_name

      - name: business_unit_2_id

      - name: business_unit_2_name

      - name: business_unit_3_name

      - name: ob_code

      - name: source

      - name: company

      - name: previous_value

  - name: gold_vti_vvn
    columns:
      - name: date
        test:
          - not_null

      - name: value

      - name: value_type

      - name: expense_code

      - name: expense_type_5_id

      - name: expense_type_5_name

      - name: department_code

      - name: business_unit_1_id

      - name: business_unit_1_name

      - name: business_unit_2_id

      - name: business_unit_2_name

      - name: business_unit_3_id

      - name: business_unit_3_name

      - name: ob_code

      - name: source

      - name: previous_value

      - name: str_value

  - name: gold_vti_group
    columns:
      - name: date
        test:
          - not_null

      - name: value

      - name: value_type

      - name: expense_code

      - name: expense_type_5_id

      - name: expense_type_5_name

      - name: department_code

      - name: business_unit_1_id

      - name: business_unit_1_name

      - name: business_unit_2_id

      - name: business_unit_2_name

      - name: business_unit_3_id

      - name: business_unit_3_name

      - name: ob_code

      - name: source

      - name: previous_value

      - name: str_value



